ConfigVersion: 2

use:
  moving_home: true
  setting_home: true
  deleting_home: true
  renaming_home: true
  teleporting_home: true
  teleporting_spawn: true
cost:
  move_home: 10
  rename_home: 100
  set_home: 20
  delete_home: 50
  teleport_home: 2
  teleport_spawn: 10