ConfigVersion: 1
Charging:
  Moving: true
  Setting: true
  Deleting: true
  Renaming: true
  Teleporting: true
Costs:
  MoveMainHome: 5
  MoveCustomHome: 10
  RenameHome: 100
  SetMainHome: 20
  SetCustomHome: 50
  DeleteMainHome: 20
  DeleteCustomHome: 50
  TeleportMainHome: 2
  TeleportCustomHome: 5
Messages:
  CurrencySymbol: "$"
  NotEnoughMoney: "you need %COST% todo this, you currently have have %BALANCE%"
  MoneySpent: "you spent %COST% to %ACTION%"